### ISSUE TITLE
File "slash.py", line 35 [ SyntaxError: invalid syntax ]

### ISSUE THREAD

**Issue by fawaz7** [theahmadov/slash#5]
input: python slash.py help

output: 
  File "slash.py", line 35
    {color.graybg}{color.red}{color.bold}${color.reset}{color.graybg} python slash.py target@gmail.com{color.reset}""")
                                                                                                                                                                                      ^
SyntaxError: invalid syntax

tried running with python2 ,3 with no luck 
i'm using the latest version on kali

edit: 
arrow is pointing to the { triple """ quotes at the end }

**Comment by fawaz7** [comment]
Thank you for the answer, sir.
unfortunately, I did everything above with no success  
here's the output 
`File "slash.py", line 35
    {color.graybg}{color.red}{color.bold}${color.reset}{color.graybg} python slash.py target@gmail.com{color.reset}""")
                                                                                                                     ^
SyntaxError: invalid syntax`

All of the requirements are installed successfully and I did try to run it with python

**Comment by fawaz7** [comment]
Edit: 
Sorry for my previous response my problem was I had 2 versions on python installed on my system python2 and python3 
and when typing `python slash.py help` it was pointing to python 2 instead of python 3 which as you said doesn't support """
error fixed by using python3 then installing 'typer' for python 3 using this command `sudo python3.11 -m pip install typer
`
Thank you for your help @theahmadov :)

**Comment by theahmadov** [comment]
Good job. np, good luck to you : )
