### ISSUE TITLE
Some forums seem to always treated as "found"

### ISSUE THREAD

**Issue by kn1cht** [theahmadov/slash#9]
## What is happening
Results of Slash always returns `forum/arduino` and `social/weheartit`, even for ids which are obviously not exist.

## How to reproduce
`$ pwgen 12 1 | xargs python slash.py`

![image](https://user-images.githubusercontent.com/16277200/225979066-4fb64ad6-1317-4332-8803-a28e024be271.png)

## Possible cause
`https://create.arduino.cc/projecthub/.*` returns 301 Moved Permanently possibly because that URL is not used now.
I cannot find any user page under the URL. I am not familiar with current Arduino website, but maybe `https://forum.arduino.cc/u/{username}` is a user page of the Arduino forum.
(Edit: I also found `https://projecthub.arduino.cc/{username}`)

```
$ curl -I https://create.arduino.cc/projecthub/foobar           
HTTP/2 301
...
````

`https://weheartit.com/.*` returns 200 OK. However, the URL only displays a guide to smartphone apps of the service and do not show any user profile. I think non-registered user of this service cannot confirm existence of username from this URL.

```
$ curl -I https://weheartit.com/foobar
HTTP/1.1 200 OK
...
```

**Comment by theahmadov** [comment]
Hmm. You are right. I prefer myself to use text based checking again... But I quit developing this project.

**Comment by theahmadov** [comment]
Also thanks for so good comment.

**Comment by kn1cht** [comment]
As a temporary solution, how about this?

For Arduino: replace `https://create.arduino.cc/projecthub/{username}` with `https://projecthub.arduino.cc/{username}`.
For We Heart It: since unregistered users cannot confirm the existence of an account, temporarily remove it from the forum list.

**Comment by theahmadov** [comment]
Hmm, it would be good solution, let me edit.

**Comment by theahmadov** [comment]
_For We Heart It: since unregistered users cannot confirm the existence of an account, temporarily remove it from the forum list._

This is really nice solution. But sorry I dont have enough time to solve this.

**Comment by theahmadov** [comment]
I made merge request : )
